### ISSUE TITLE
Support X86 32bit

### ISSUE THREAD

**Issue by mlite** [Theldus/PBD#6]
I tried to build your code for X86 32bit, and got the following errors.  Is 32-bit supported? If not, do you have any plans to support it?

ptrace.c:102:45: error: use of undeclared identifier 'RIP'
        return (ptrace(PTRACE_PEEKUSER, child, 8 * RIP, NULL));
                                                   ^
ptrace.c:116:7: error: no member named 'rip' in 'struct user_regs_struct'; did you mean 'eip'?
        regs.rip = pc;
             ^~~
             eip
/usr/include/i386-linux-gnu/sys/user.h:145:12: note: 'eip' declared here
  long int eip;
           ^
ptrace.c:130:45: error: use of undeclared identifier 'RBP'
        return (ptrace(PTRACE_PEEKUSER, child, 8 * RBP, NULL));
                                                   ^
ptrace.c:145:42: error: use of undeclared identifier 'RSP'
        sp = ptrace(PTRACE_PEEKUSER, child, 8 * RSP, NULL);
                                                ^
4 errors generated.

**Comment by Theldus** [comment]
Hi mlite,
> I tried to build your code for X86 32bit, and got the following errors.

Unfortunately, x86 is not supported at the moment, only x64. But, how do you accomplished to get these errors? I mean, there is a check on the makefile that checks if the target system is x86 or not, or have you trying to do a cross-compiling on a 64-bit system?

> Is 32-bit supported? If not, do you have any plans to support it?

Yep, I do plan to support x86 systems. I just support x64 because it seems to have a 'movement' towards x64 and everything on 32-bit world is being 'deprecated'. I do not agree with it but I had to 'pin' one arch before starting the PBD development; but yeah, it shouldn't be so much harder to port to x86.

**Comment by Theldus** [comment]
@mlite I will start working on PBD support for x86, and I can spend a week or two to complete. All the changes will be sent to the `x86_support` branch (yet to be pushed), so you can track my progress. When I finish, I'll submit a PR and mention you there so you can get notified.
